ERROR 2015-10-30 04:47:53,160 base 20654 139668970735360 Internal Server Error: /
Traceback (most recent call last):
  File "/home/yongsong/VirtualEnvs/hackathon/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 119, in get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/home/yongsong/VirtualEnvs/hackathon/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 366, in resolve
    for pattern in self.url_patterns:
  File "/home/yongsong/VirtualEnvs/hackathon/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 402, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/yongsong/VirtualEnvs/hackathon/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 396, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/media/sf_workspace/zhang-repo/hackathon_microblog/hackathon_microblog/urls.py", line 3, in <module>
    from hackathon_microblog.microblog import views as microblog_views
  File "/media/sf_workspace/zhang-repo/hackathon_microblog/hackathon_microblog/microblog/views.py", line 6, in <module>
    from gtoext.contrib.garena_oauth.user import AuthGarenaUser, PermitGarenaUser302, PermitGarenaUser
  File "/home/yongsong/VirtualEnvs/hackathon/local/lib/python2.7/site-packages/gtoext/contrib/garena_oauth/user.py", line 17, in <module>
    BASE_MODULE_PATH = settings.GTOEXT_GARENA_OAUTH.get('base_path', '/garena_oauth')
  File "/home/yongsong/VirtualEnvs/hackathon/local/lib/python2.7/site-packages/django/conf/__init__.py", line 49, in __getattr__
    return getattr(self._wrapped, name)
AttributeError: 'Settings' object has no attribute 'GTOEXT_GARENA_OAUTH'
ERROR 2015-10-30 04:47:53,510 base 20654 139668960192256 Internal Server Error: /favicon.ico
Traceback (most recent call last):
  File "/home/yongsong/VirtualEnvs/hackathon/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 108, in get_response
    response = middleware_method(request)
  File "/home/yongsong/VirtualEnvs/hackathon/local/lib/python2.7/site-packages/django/middleware/common.py", line 74, in process_request
    if (not urlresolvers.is_valid_path(request.path_info, urlconf) and
  File "/home/yongsong/VirtualEnvs/hackathon/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 647, in is_valid_path
    resolve(path, urlconf)
  File "/home/yongsong/VirtualEnvs/hackathon/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 522, in resolve
    return get_resolver(urlconf).resolve(path)
  File "/home/yongsong/VirtualEnvs/hackathon/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 366, in resolve
    for pattern in self.url_patterns:
  File "/home/yongsong/VirtualEnvs/hackathon/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 402, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/yongsong/VirtualEnvs/hackathon/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 396, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/media/sf_workspace/zhang-repo/hackathon_microblog/hackathon_microblog/urls.py", line 3, in <module>
    from hackathon_microblog.microblog import views as microblog_views
  File "/media/sf_workspace/zhang-repo/hackathon_microblog/hackathon_microblog/microblog/views.py", line 6, in <module>
    from gtoext.contrib.garena_oauth.user import AuthGarenaUser, PermitGarenaUser302, PermitGarenaUser
  File "/home/yongsong/VirtualEnvs/hackathon/local/lib/python2.7/site-packages/gtoext/contrib/garena_oauth/user.py", line 17, in <module>
    BASE_MODULE_PATH = settings.GTOEXT_GARENA_OAUTH.get('base_path', '/garena_oauth')
  File "/home/yongsong/VirtualEnvs/hackathon/local/lib/python2.7/site-packages/django/conf/__init__.py", line 49, in __getattr__
    return getattr(self._wrapped, name)
AttributeError: 'Settings' object has no attribute 'GTOEXT_GARENA_OAUTH'
ERROR 2015-10-30 04:47:53,660 base 20654 139668960192256 Internal Server Error: /favicon.ico
Traceback (most recent call last):
  File "/home/yongsong/VirtualEnvs/hackathon/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 108, in get_response
    response = middleware_method(request)
  File "/home/yongsong/VirtualEnvs/hackathon/local/lib/python2.7/site-packages/django/middleware/common.py", line 74, in process_request
    if (not urlresolvers.is_valid_path(request.path_info, urlconf) and
  File "/home/yongsong/VirtualEnvs/hackathon/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 647, in is_valid_path
    resolve(path, urlconf)
  File "/home/yongsong/VirtualEnvs/hackathon/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 522, in resolve
    return get_resolver(urlconf).resolve(path)
  File "/home/yongsong/VirtualEnvs/hackathon/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 366, in resolve
    for pattern in self.url_patterns:
  File "/home/yongsong/VirtualEnvs/hackathon/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 402, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/yongsong/VirtualEnvs/hackathon/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 396, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/media/sf_workspace/zhang-repo/hackathon_microblog/hackathon_microblog/urls.py", line 3, in <module>
    from hackathon_microblog.microblog import views as microblog_views
  File "/media/sf_workspace/zhang-repo/hackathon_microblog/hackathon_microblog/microblog/views.py", line 6, in <module>
    from gtoext.contrib.garena_oauth.user import AuthGarenaUser, PermitGarenaUser302, PermitGarenaUser
  File "/home/yongsong/VirtualEnvs/hackathon/local/lib/python2.7/site-packages/gtoext/contrib/garena_oauth/user.py", line 17, in <module>
    BASE_MODULE_PATH = settings.GTOEXT_GARENA_OAUTH.get('base_path', '/garena_oauth')
  File "/home/yongsong/VirtualEnvs/hackathon/local/lib/python2.7/site-packages/django/conf/__init__.py", line 49, in __getattr__
    return getattr(self._wrapped, name)
AttributeError: 'Settings' object has no attribute 'GTOEXT_GARENA_OAUTH'
